# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY ubuntu-intune/build_files /

# Base Ubuntu Image
FROM docker.io/library/ubuntu:22.04

COPY ubuntu-intune/system_files /

ARG DEBIAN_FRONTEND=noninteractive
RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache/apt \
    --mount=type=cache,dst=/var/log \
    --mount=type=cache,dst=/var/lib/apt \
    --mount=type=cache,dst=/var/lib/dpkg/updates \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build
